spring:
    datasource: # MariaDB configuration
        url: jdbc:mariadb://mariadb:3306/supermarket_db
        username: uniwa_admin
        password: adminUNIWA
        driver-class-name: org.mariadb.jdbc.Driver

    jpa: # Java Persistence API
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    docker:
        compose:
            enabled: true
            files: server/server.yml
    logging:
        level:
            org.springframework.web: DEBUG
            org.hibernate:
                .SQL: INFO
                .type.descriptor.sql.BasicBinder: TRACE 